variables:
    DOCKER_REGISTRY_HOST: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote

image: docker:20.10

stages:
    - build
    - deploy-test

build-candidate:
    stage: build
    only:
        - tags
    before_script:
        - apk add --no-cache python3 py-pip git
        - pip install awscli==1.18.69
    script:
        - docker build --build-arg APP_ENV=test -t candidate-v2:${CI_COMMIT_TAG}-test .

deploy-to-test:
  stage: deploy-test
  only:
    - tags
  when: manual
  variables:
    APP_ENV: TEST
    AWS_ACCESS_KEY_ID: $AWS_S3_APP_ACCESS_KEY_ID_TEST
    AWS_SECRET_ACCESS_KEY: $AWS_S3_APP_SECRET_ACCESS_KEY_TEST
  script:
    - docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_S3_APP_ACCESS_KEY_ID_TEST -e AWS_SECRET_ACCESS_KEY=$AWS_S3_APP_SECRET_ACCESS_KEY_TEST -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION candidate-v2:${CI_COMMIT_TAG}-test s3 sync /var/app/dist/ s3://vtest-test-candidate-app/dist/
  environment:
    name: test
  after_script:
    - docker rmi candidate-v2:${CI_COMMIT_TAG}-test
    - docker image prune -f

